### ISSUE TITLE
Insert own Smileys (update-safe)

### ISSUE THREAD

**Issue by Xendiadyon** [cliffparnitzky/TinyMceEmoticons#1]
Hello,

I try to insert my own Smileys to the TinyMCE in Contao 4 using your extension.
When installing with composer, a symlink in assets/tinymce4/js/plugins/emoticons is made, which leads to the vendor/cliffparnitzky/tiny-mce-emoticons folder.
If I would make changes there, it would not be update-safe.
How could I edit the plugin.min.js and keep my version after an update?

Thank you.

**Comment by cliffparnitzky** [comment]
Oh this is not that easy. I think the best way will be to create an own plugin like this: https://github.com/rsclg/RscTinyMceTriathlonIcons

**Comment by cliffparnitzky** [comment]
@Xendiadyon for further information please contact me via email.

**Comment by Xendiadyon** [comment]
Thank you. I managed to edit the Contao be_tinyMCE.html5 template and to add the script which is used by your extension TinyMCEPluginLoader. So I am able to "hook in" a self-edited Version of your Smileys!
